DROP TABLE IF EXISTS support_group_news_article_response_sent_to_user_email;
DROP TABLE IF EXISTS support_group_news_article_response;
DROP TABLE IF EXISTS support_group_news_article_sent_to_user_email;
DROP TABLE IF EXISTS support_group_news_article ;
DROP TABLE IF EXISTS pilot_users;
DROP TABLE IF EXISTS  sms_in;
DROP TABLE IF EXISTS schedule_rule_for_request_type;
DROP TABLE IF EXISTS schedule_rule_for_user_twitter;
DROP TABLE IF EXISTS schedule_rule_for_user_telephone;
DROP TABLE IF EXISTS schedule_rule_for_user_email;
DROP TABLE IF EXISTS schedule_rule;
DROP TABLE IF EXISTS simple_schedule_request_type_rule;
DROP TABLE IF EXISTS request_response_sent_to_user_telephone; 
DROP TABLE IF EXISTS request_response_sent_to_user_twitter ;
DROP TABLE IF EXISTS request_response_sent_to_user_email;
DROP TABLE IF EXISTS request_response;
DROP TABLE IF EXISTS request_sent_to_user_telephone ;
DROP TABLE IF EXISTS request_sent_to_user_twitter; 
DROP TABLE IF EXISTS request_sent_to_user_email ;
DROP TABLE IF EXISTS request_to_user ;
DROP TABLE IF EXISTS request_has_type;
DROP TABLE IF EXISTS request;
DROP TABLE IF EXISTS request_type;
DROP TABLE IF EXISTS user_in_group;
DROP TABLE IF EXISTS support_group;
DROP TABLE IF EXISTS user_admins_white_label;
DROP TABLE IF EXISTS white_label;
DROP TABLE IF EXISTS user_session;
DROP TABLE IF EXISTS user_on_holiday;
DROP TABLE IF EXISTS  user_telephone;
DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS user_twitter; 
DROP TABLE IF EXISTS user_email;
DROP TABLE IF EXISTS user_account ;